version: '3'
services:
  backend:
    image: ethiclo
    environment:
      - DB_URL=${DB_URL}
      - GDATABASE=${GDATABASE}
      - PGHOST=${PGHOST}
      - PASSWORD=${PASSWORD}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - BROWSERLESS_API_KEY=${BROWSERLESS_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}